---
- name: Create instance using terraform script
  hosts: 35.204.152.104
  become: true
  become_method: sudo
  tasks:
    - name: Create destination directory
      file:
        path: /terraform_path
        state: directory
        mode: 0755
      
    - name: Download Terraform script
      get_url:
        url: https://storage.googleapis.com/jimmy-playbooks/TerraformScript.tf
        dest: /terraform_path/main.tf

    - name: Terraform Init
      shell: cd terraform_path/ && terraform init
   
    - name: Terraform Apply
      shell: cd terraform_path/ && terraform apply "planfile"
