---
- name: Create instance using terraform script
  hosts: 35.204.152.104
  become: true
  become_method: sudo
  
  vars:
    download_url: "cu"
    terraform_path: "terraform_path"
  
  tasks:
    - name: Remove Terraform
      file:
        state: absent
        path: "{{ terraform_path }}"
   
    - name: Create terraform directory if it does not exist
      ansible.builtin.file:
        path: "{{ terraform_path }}"
        state: directory
        mode: '0777'

    - name: Download Terraform script
      get_url:
        url: "{{ download_url }}"
        dest: "{{ terraform_path }}/main.tf"
 
    - name: Run Terraform apply
      ansible.builtin.command: terraform apply -auto-approve
      args:
        chdir: "{{ terraform_path }}"
