- name: Download and extract file
  hosts: all
  become: true
  
  tasks:
    shell: |
      cd /
      curl -o /terraform/file.zip https://storage.cloud.google.com/jimmy-playbooks/TerraformScriptZip
      unzip /terraform/file.zip -d /terraform/
    args:
      executable: /bin/bash
