---
- name: Download and extract file
  hosts: all
  
  tasks:
    - name: Relocate root
      shell: cd /

    - name: Download file
      shell: wget https://storage.cloud.google.com/jimmy-playbooks/TerraformScript.tf
