---
- name: Download a file
  hosts: all
  tasks:
    - name: Relocate root
      shell: cd /

    - name: Download a file
      get_url:
        url: "https://storage.cloud.google.com/jimmy-playbooks/TerraformScript.tf"
        dest: "/terraform/TerraformScript.tf"
