---
- name: Download and extract file
  hosts: all
  
  tasks:
    - name: Become sudo
      shell: sudo su

    - name: Relocate root
      shell: cd /
        
    - name: Download file
      get_url:
        url: https://storage.cloud.google.com/jimmy-playbooks/TerraformScript.tf
        dest: /terraform/
