- name: Download and extract file
  hosts: all
  become: true
  
  tasks:
    - name: Relocate root
      shell: cd /

    - name: Download file
      shell: curl -o /terraform/file.zip https://storage.cloud.google.com/jimmy-playbooks/TerraformScriptZip
    
    - name: Extract file
      shell: unzip /terraform/file.zip -d /terraform/
      
    args:
      executable: /bin/bash
