---
- name: Download Terraform script
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Create destination directory
      file:
        path: /terraform_path
        state: directory
        mode: 0755
      
    - name: Download Terraform script
      get_url:
        url: https://storage.cloud.google.com/jimmy-playbooks/TerraformScript.tf
        dest: /terraform_path/TerraformScript.tf
